### ISSUE TITLE
Respectfully request that repo is licensed under open source

### ISSUE THREAD

**Issue by KathyReid** [abcnews/data-australian-political-donations#2]
G'day @drzax and @blakebutcher, 
Firstly enormous kudos for the work that you've done here and for using data so skilfully in journalism. Could I respectfully request that this repo is open source licensed so that it can be collaboratively contributed to? May I suggest 
https://choosealicense.com/
Kind regards, 
Kathy

Full disclosure: I am a volunteer board member for @linuxaustralia, an organiser for @govhack Geelong and do paid work in data visualisation.

**Comment by drzax** [comment]
Good suggestion @KathyReid. The lack of a license is an oversight, thank you for bringing it to our attention. 

The original data from the AEC is licensed under the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license. I expect we will apply the same license to our additions / remix of the data. The code in this repo may be licensed differently.

I will seek organisational advice and apply appropriate licenses as soon as possible.

**Comment by drzax** [comment]
@mattliddy can you weigh in on this?

**Comment by KathyReid** [comment]
@drzax Excellent points, thanks for such a speedy response!

**Comment by mattliddy** [comment]
I think CC BY 4.0 sounds like an appropriate approach. Thanks for raising the question Kathy.
