### ISSUE TITLE
Source of Categorisation

### ISSUE THREAD

**Issue by TheRealCreamCheesus** [abcnews/data-australian-political-donations#4]
Wow! This is a great peace of journalism. Very informative and detailed for such a serpentine issue. 

I'm interested in how the categorisation for each entry by industry was completed. The datasset appears to be near identical to that used at http://democracyforsale.net/search-aec Did you source the original data/tags from there or did you start from scratch?

**Comment by drzax** [comment]
The Greens' list was definitely a dataset we looked at, but decided it was important that we created our own categorisations. The final list of categories and categorisations we ended up with are, as you say, similar to the Greens' list, but not identical.
